[timetable]
[[timetable.days]]
day = "Пт"
[[timetable.days.classes]]
time = "10:00-11:30"
parity = "четная неделя"
building = "ул.Ломоносова, д.9, лит. М"
classroom = "актовый зал"
title = "Основы профессиональной деятельности(Лек)"
teacher = "Клименков Сергей Викторович"
format = "Очно - дистанционный"

[[timetable.days.classes]]
time = "11:40-13:10"
parity = "четная неделя"
building = "ул.Ломоносова, д.9, лит. М"
classroom = "актовый зал"
title = "Программирование(Лек)"
teacher = "Письмак Алексей Евгеньевич"
format = "Очно - дистанционный"


